### ISSUE TITLE
Multiple places to define sampling fraction within same data chain

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#249] opened 2022-10-19 18:40 UTC
See first comment.

**Comment by veprbl** [comment] 2022-10-19 20:18
There are several sampling fractions:
https://github.com/eic/EICrecon/blob/afe3599f6b04498d9069724c58851a0232908639/src/tools/default_flags_table/reco_flags.py#L43
https://github.com/eic/EICrecon/blob/afe3599f6b04498d9069724c58851a0232908639/src/tools/default_flags_table/reco_flags.py#L66
https://github.com/eic/EICrecon/blob/afe3599f6b04498d9069724c58851a0232908639/src/tools/default_flags_table/reco_flags.py#L75
and we are wondering if they "stack" repeatedly, or the sampling fraction for clustering is ignored by the algorithm.

**Comment by DraTeots** [comment] 2022-10-19 21:03
As it was said, we can use just one flag per name instead of 3: 

```
BEMC:sampleFraction
```
Then factories will use just this flag. But then some renaming should be done for other calorimetry flags. 

Now flags are assigned to underlying algorithms. So those 3 samplingFractions how it goes to 3 different algorithms. 

We can do it like: 

```bash
BEMC:globalDetectorFlag1
BEMC:globalDetectorFlag2

# Then per algorithm
BEMC:Algo1:Flag1
BEMC:Algo1:Flag2

BEMC:Algo2:AnotherFlag
# ...
```

Or partition like `digi`, `reco`

```bash

BEMC:Digi:Flag1
BEMC:Digi:Flag2

BEMC:Reco:Flag1
BEMC:Reco:Flag2
```

Flags are just strings, so we can use any scheme. Whatever experts decide. But it should be somehow coherent.

**Comment by DraTeots** [comment] 2023-03-06 16:58
Depends on how it is judged. Either this issue is gone with reco_flags or won't fix until we review how we do configuration in general. Technically it is possible but how it implemented now or will be implemented in algorithms won't fix this. In both cases the issue is to be closed.

**Closed by DraTeots** 2023-03-06 16:58 UTC
Labels: meta:wontfix, part:detectors, reco:defaults and flags
