### ISSUE TITLE
Thread failure and backtrace should result in eicrecon end, not timeout

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#323] opened 2022-11-08 19:40 UTC
In one of the simulation production jobs, a thread failed, generated a backtrace, but the eicrecon run was not interrupted right away. Instead, it sat there for an additional 300 seconds waiting for the inevitable timeout to happen.

```
Thread model: pthreads
47379043882560: 
       `- /lib/x86_64-linux-gnu/libc.so.6 (0x2b17244bcaa0)
        `- TBranchElement::SetAddressImpl(void*, bool) (0x2b17288fe897)
         `- TBranchElement::SetAddressImpl(void*, bool) (0x2b17288fea13)
          `- podio::ROOTReader::getCollection(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::tuple<TClass const*, TClass const*, unsigned long> > const&) (0x2b1728820c5d)
           `- podio::ROOTReader::readCollection(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (0x2b17288213c9)
            `- podio::EventStore::doGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, podio::CollectionBase*&, bool) const (0x2b1728836df0)
             `- podio::EventStore::get(int, podio::CollectionBase*&) const (0x2b17288371e8)
              `- JEventSourcePODIOsimple::GetEvent(std::shared_ptr<JEvent>) (0x2b172872c01c)
               `- eicrecon (0x564681bd8764)
                `- eicrecon (0x564681bdf61f)
                 `- eicrecon (0x564681be4819)
                  `- /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x2b172423a3d3)
                   `- /lib/x86_64-linux-gnu/libc.so.6 (0x2b172450684a)
                    `- clone (0x2b1724589530)


[INFO] Status: 83 events processed  2.0 Hz (1.3 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.3 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.3 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.3 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (1.1 Hz avg)
...
[INFO] Status: 83 events processed  0.0 Hz (0.2 Hz avg)
[INFO] Status: 83 events processed  0.0 Hz (0.2 Hz avg)
[FATAL] Detected timeout in worker! Stopping.
[INFO] Merging threads ...
[INFO] JArrow: Finalizing JEventSource '/srv/FULL/22.11.0/epic_arches/DIS/NC/18x275/minQ2=1000/pythia8NCDIS_18x275_minQ2=1000_beamEffects_xAngle=-0.025_hiDiv_vtxfix_1_022.0004.edm4hep.root' (JEventSourcePODIOsimple)
[INFO] JArrow: Finalizing JEventProcessor 'JEventProcessorPODIO'
[INFO] JArrow: Finalizing JEventProcessor ''
```

**Comment by nathanwbrei** [comment] 2022-11-12 04:37
This issue is caused by https://github.com/JeffersonLab/JANA2/issues/158, which has already been fixed and will be in the next release.

**Closed** 2022-11-23 19:17 UTC
