### ISSUE TITLE
PODIO issues

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#165] opened 2022-09-28 13:48 UTC
This gathers issues with podio to try and make a complete and clear list that can then be addressed with the podio authors. It is being done here so that details can be gathered over a bit of time to make it more complete rather than submitting these as piecemeal issues to the podio Github.
----------------------------------------------------------------------

1. We are basically forced into using the generated Collection classes as containers for the data objects. Internal relations between objects (e.g. which truth hit a digitized hit came from) is handled by the ObjectID that is buried in the `m_obj` member of the top-level object class. The `m_obj` pointer is a private member.
For example, creating a `edm4hep::CalorimeterHit` object using the standard constructor that passes in all data members, automatically calls the default constructor for the `edm4hep::CalorimeterHitObj` member. This sets the ObjectID fields of `m_obj` to `podio::ObjectID::untracked`. There appears to be no way to modify this value other than to place the object into a `edm4hep::CalorimeterHitCollection` which is given special status as a friend class of `edm4hep::CalorimeterHit`. 
The bottom line is it is impossible to use the the ObjectID mechanism to track object relations unless you use the Collection mechanism to manage the objects. Either the ObjectID should be allowed to be manipulated by outside code, or it should be taken out of the "Obj" classes and its functionality moved completely into the Collection classes since management of it is restricted to there anyway.

2. Denying access to the "Data" classes that hold the actual data structures through the use of `private:` severely limits implementing any kind of I/O implementation other than exactly what comes with podio (e.g. `RootReader` and `RootWriter`). I understand the goal of making the actual data storage opaque so that it can be changed underneath without modification of user code. E.g. switch from arrays of structures to structures of arrays. However, without access to the low-level "Data" objects, we are forced to use Collection classes to prepare data for writing via the `prepareForWrite` method. The only other option would be to manually code calling all of the getter methods to extract individual values. If we had access to "Data" objects, we could use ROOT directly to read/write without having to do a deep copy of every object into a collection.

**Comment by faustus123** [comment] 2022-09-28 16:17
3. Having both a Mutable and immutable version of each class causes an inefficient programming pattern. Specifically, one instantiates a Mutable object, modifies it,  and then uses it to construct an object of the immutable variety. This wastes resources and slows things down unnecessarily. The same functionality can be achieved using `const` which effectively turns a mutable object into an immutable one (thus, saving the second object instantiation). Removing the mutable classes would also reduce the shear number of classes podio generates.

**Comment by DraTeots** [comment] 2022-09-29 06:06
On #3. Podio objects work as shared pointers. So one shared pointers have SetX functions and the others are not. I wouldn't say that copying shared pointers around is resource wasteful. const-ness in C++ is so coarse that this might be a good approach to achieve real and more controllable const-ness. 

IMO how PODIO is implemented has two implications. One is easy to fix and the other is kind of fundamental. 

1. Having mutable and unmutable pointers might be good and in fact is used as a less-bug-architecture in many languages (see React and other frontend data storages as example). But in PODIO it is done extremely inconvenient. What objects can be done from what? How to do 
- clone-mutate-clone (when object is immutable and one has to copy it in order to mutate). 
- or clone-mutate-lock (when object is immutable so you create a mutable copy which you lock then)? 
API don't have it. So it looks like under-designed immutable data storage from javascript world. 

2. More fundamental problem is that if PODIO objects are de facto shared pointers to a private proxy-object and their intended use is on stack. In another words, in JANA we use it like: 

```C++
std::vector<edm4hep::SimHit*>()
```

But in reality its nature is: 

```C++
std::vector<  std::shared_pointer<edm4hep::SimHitObj>  * >()
```

Isn't passing raw pointers to shared pointers looks awkward? Who passes around raw pointers to shared pointers? But that is what we have to do. Nothing criminal in terms of C++ language. Bun then ownership and life time problems kick in between Collections and JANA Factories it becomes clumsy. 

P.S. Not sure these words are for developers but rather a brainstorming in this ticket on what seems wrong

**Comment by faustus123** [comment] 2022-09-29 12:27
@DraTeots makes some clearly good points. There is definitely an awkwardness to what is effectively managing a list of pointers to a shared pointer. I will add a couple of comments:

1. podio implements not only its own substitute for `std::shared_ptr`, but it does this by creating a custom "shared pointer" class for each data type in the model. Actually two since it creates a Mutable and non-Mutable version. What it desperately lacks is the ability to get at the underlying object it is wrapping. `std::shared_ptr` provides a `get()` method for this.

2. In our particular use-case, we have lots of objects that have a shared lifetime: the processing of the current event. All of the event-level objects that the framework manages are guaranteed to exist and be immutable (after creation in the factory) until the processing of the event is complete. Podio's attempt to manage this lifetime independently leads to the clumsiness @DraTeots very correctly points to.

One could argue whether shared pointers should be used everywhere or not. IMHO leveraging the somewhat unique case we have of shared lifetimes saves having to create/delete numerous shared pointer objects for every data object in every event. Even though the shared pointers are small, this still adds up. The main point though is that we should have the flexibility to implement that or not in the framework without podio forcing it.

So regarding item 3. : I still think we would be better off keeping the class that is currently "Mutable" and dropping the immutable version (with appropriate name migration). Mainly because, IMHO, `const` better serves us as this at the language level as opposed to implementing it through class design.

**Comment by DraTeots** [comment] 2022-09-29 15:33
Can `const MutableObj` be used for link counting then? (mutate state) So is then the essential problem that links counting and "Objectification" of POD is mixed together?

**Comment by nathanwbrei** [comment] 2022-10-11 14:01
Finding the transitive closure of your collections.

Suppose you want to write _some_ of the collections in the event store but not all. (The motivation for this is that re-saving all of the data that was read from the input file gets unbearably slow.) Call this set S. You want to save not just every collection in S, but also every collection referenced by those. Call this set T.

The problem is that there's nothing constraining references to always belong to a certain collection, merely a certain type. Thus, you don't know your collection dependencies upfront. Event #1000 can introduce a dependency on a collection that wasn't detectable previously. I'm forced to either add the ability to backfill collections, or to save down every collection of the referenced type just in case it gets referenced. 

What I'd like to add a constraint which says that for a given collection, its references of a given type must belong to one exact collection id (though I'd settle for one of a set of collection ids.) 

PODIO does an admirable job understanding the relational model (rather than badly reinventing it from scratch while remaining loudly in denial). However, it drops the ball with foreign keys.

**Comment by nathanwbrei** [comment] 2022-10-17 19:04
Generally I believe that using PODIO collections is necessary if we are going to use object-orientation to enforce correct object references. However, I do not believe that collections are sufficient. The event store or frame or whatever is an essential part of this.
- We need some kind of constraint that all collections that can refer to each other live within the same event store
- We need some kind of constraint that collection IDs are consistent between different files. This is particularly true if we want to use PODIO for checkpointing.

**Comment by DraTeots** [comment] 2023-03-06 16:36
That were question before the discussion with PODIO team. The discussion happened as well future collaboration. We may close this

**Closed by DraTeots** 2023-03-06 16:36 UTC
Labels: meta:question, part:io, part:integration
