### ISSUE TITLE
All exceptions are treated as warnings by `JEventProcessorPODIO`

### ISSUE THREAD

**Issue by veprbl** [eic/EICrecon#532] opened 2023-03-09 11:53 UTC
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released):
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. run eicrecon with `-PEcalBarrelSciGlassProtoClusters:splitCluster=1`, it is currently producing what seems to be a legitimate exception
2. observe that the exception is ignored, and instead a warning is issued

```
[2023-03-09 06:43:38.752] [JEventProcessorPODIO] [warning] Exception adding PODIO type 'edm4eic::Cluster:EcalBarrelSciGlassMergedClusters': std::exception.
```

There are plenty of warnings like this one:
```
[2023-03-09 06:43:38.770] [JEventProcessorPODIO] [warning] Exception adding PODIO type 'edm4eic::ReconstructedParticle:ReconstructedParticles': Could not find JFactoryT<edm4hep::SimCalorimeterHit> with tag=EcalEndcapNHits.
```
so it's impossible to notice the relevant one

### Expected Result: (what do you expect when you execute the steps above)
- EICrecon terminates with an exit code
- (extra) Exceptions are not used as part of a routine control flow

**Comment by DraTeots** [comment] 2023-03-11 06:56
I believe this one to be duplicate of

https://github.com/eic/EICrecon/issues/316

**Closed** 2023-03-11 08:26 UTC
Labels: meta:duplicate, part:services, part:io
