### ISSUE TITLE
Restore license lines and original author lists to files in algorithms directory

### ISSUE THREAD

**Issue by faustus123** [eic/EICrecon#186] opened 2022-10-06 01:53 UTC
Several files in the algorithms branch of the src tree do not have the header comments from the original juggler algorithm files that specify the license the files were developed under and the original author list. These need to be restored. An example of what it should look similar to is here:

[src/algorithms/digi/SmearedFarForwardParticles.h]()

Here is an example of one that is missing the lines:
[src/algorithms/calorimetry/CalorimeterHitDigi.h]()

Each file may be different (particularly the author list) so needs to be restored by going back to the original juggler files.

**Comment by DraTeots** [comment] 2022-10-06 15:19
This is kind of a duplicate of this https://github.com/eic/EICrecon/issues/65 but phrased better.

**Comment by DraTeots** [comment] 2023-03-06 16:40
Completed with #65

**Closed by DraTeots** 2023-03-06 16:40 UTC
